import SigninForm from "@/components/form/SigninForm";

import { Metadata } from "next";
import { FC } from "react";

export const metadata: Metadata = {
  title: "House -",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg", // Default favicon
    shortcut: "/icon.svg",
    apple: "/icon.svg",
  },
};

interface pageProps {}

const page: FC<pageProps> = ({}) => {
  return (
    <div className="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
      <div className="sm:mx-auto sm:w-full sm:max-w-sm">
        <SigninForm />
      </div>
    </div>
  );
};

export default page;
