import type { Metadata } from "next";
import Navbar from "@/layout/Navbar";
import Footer from "@/layout/Footer";
import ContactForm from "@/components/ContactForm";
import FAQ from "@/components/FAQ";

export const metadata: Metadata = {
  title: "House",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg", // Default favicon
    shortcut: "/icon.svg",
    apple: "/icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <div className="flex-grow flex-1">{children}</div>
      <div className="min-h-screen bg-gray-50 py-12">
        <ContactForm />
      </div>
      <FAQ />
      <Footer />
    </>
  );
}
